web:
   build: .
   container_name: vs-loyalty-web
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "8011:80"
   volumes:
     - ./app:/var/www/html/
   links:
     - db
db:
   image: mariadb
   restart: always
   volumes:
   - ./mysql:/var/lib/mysql
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
   ports:
   - "8889:3306"